version: "3.9"

services:
  portainer:
    image: portainer/portainer-ce:2.0.0
    command: --tlsskipverify
    volumes:
      - ./storage/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8000:8000
      - 9000:9000